
addpath('/disk7/ziweili/CESM_LENS/source')

pwd_str = pwd;

mat_filenames = {'CESM_6hourly.mat', ...
                 'CESM_daily.mat', ...
                 'GFDL_6hourly.mat', ...
                 'GFDL_6hourly_full_b.mat', ...
                 'GFDL_daily.mat'};


output_path = './data/';
if ~exist(output_path)
    mkdir(output_path);
end

for f_ind = 1 : length(mat_filenames)
    disp(['calculating ', mat_filenames{f_ind}])
    if strcmp(mat_filenames{f_ind}, 'CESM_daily.mat')
        path = '/disk7/ziweili/CESM_LENS/exp/';
        filenames = {[path, '001_2D_varsig_Q_findcenter_daily/plot_diagnostic.mat'], ...
                     [path, '002_2D_varsig_Q_findcenter_daily/plot_diagnostic.mat'], ...
                     [path, '003_2D_varsig_Q_findcenter_daily/plot_diagnostic.mat'], ...
                     [path, '004_2D_varsig_Q_findcenter_daily/plot_diagnostic.mat'], ...
                     [path, '005_2D_varsig_Q_findcenter_daily/plot_diagnostic.mat'], ...
                     [path, '035_2D_varsig_Q_findcenter_daily/plot_diagnostic.mat'], ...
                    };
        GFDL = false;
    elseif strcmp(mat_filenames{f_ind}, 'CESM_6hourly.mat')
        path = '/disk7/ziweili/CESM_LENS/exp/';
        filenames = {[path, '001_2D_varsig_Q_findcenter/plot_diagnostic.mat'], ...
                     [path, '002_2D_varsig_Q_findcenter/plot_diagnostic.mat'], ...
                     [path, '003_2D_varsig_Q_findcenter/plot_diagnostic.mat'], ...
                     [path, '004_2D_varsig_Q_findcenter/plot_diagnostic.mat'], ...
                     [path, '005_2D_varsig_Q_findcenter/plot_diagnostic.mat'], ...
                     [path, '035_2D_varsig_Q_findcenter/plot_diagnostic.mat'], ...
                     };
        GFDL = false;
    elseif strcmp(mat_filenames{f_ind}, 'GFDL_6hourly_full_b.mat')
        path = '/disk7/ziweili/test1_GFDL/exp/';
        filenames = {[path, '2D_varsig_Q_findcenter_wb/plot_diagnostic.mat']};
        GFDL = true;
    elseif strcmp(mat_filenames{f_ind}, 'GFDL_daily.mat')
        path = '/disk7/ziweili/test1_GFDL/exp/';
        filenames = {[path, '2D_varsig_Q_findcenter_daily_99.5/plot_diagnostic.mat']};
        GFDL = true;
    elseif strcmp(mat_filenames{f_ind}, 'GFDL_6hourly.mat')
        path = '/disk7/ziweili/test1_GFDL/exp/';
        filenames = {[path, '2D_varsig_Q_findcenter/plot_diagnostic.mat']};
        GFDL = true;
    end

    ensemble_read_data_v1;

    plot_level = 50000;
    plot_level_name = [num2str(plot_level/100.), 'hPa'];
    plevels = [100000, 97500, 95000, 92500, 90000, 87500, 85000, 82500, 80000, 77500, 75000, 70000, 65000, ...
                60000, 55000, 50000, 45000, 40000, 35000, 30000, 25000, 22500, 20000, 17500, 15000]';
    plot_ind = plevels == plot_level;

    % from 3D to 2D
    names = who;
    for n = 1 : length(names)
        if length(eval(['size(', names{n}, ')'])) == 3
            temp = eval(names{n});
            eval([names{n}, ' = temp(:, :, plot_ind);'])
        end
    end

    save([output_path, mat_filenames{f_ind}], ...
    'omega_h'   , 'omega_r'   , 'omega_QG_h', 'omega_QG_r', ...
    'precip_h'  , 'precip_r'  , 'Adv_h'     , 'Adv_r'     , ...
    'C_h'       , 'C_r'       , 'J_h'       , 'J_r'       , ...
    'sigma_h'   , 'sigma_r'   , 'k2_h'      , 'k2_r'      , ...
    'l2_h'      , 'l2_r'      , 'm2_h'      , 'm2_r'      , ...
    'dtheta_dp_ma_h', 'dtheta_dp_ma_r', 'sigma_star_h'         , 'sigma_star_r'         , ...
    'num_event_h'   , 'num_event_r'   , 'num_event_discarded_h', 'num_event_discarded_r', ...
    'Plevels', 'F0', 'kappa', 'lat_series', 'lat_indices', 'lat', 'lon')

end


